# Generated by Django 4.0.3 on 2022-04-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoggy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='hotel',
            new_name='cuisines',
        ),
        migrations.RenameField(
            model_name='cuisine',
            old_name='zoggys',
            new_name='hotels',
        ),
    ]
